### ISSUE TITLE
Peer-review: comments from Omar

### ISSUE THREAD

**Issue by omvazque** [teokem/project-work-2021-cdgomezo#2]
Hi,

I like you Jupyter notebook. I find it quite pedagogical and I have only few comments.

1. Can you please add a small description in your GitHub repository, the purpose of your repository and what people will find on it (enviroment, README,... files ).
2. Can you add instructions on how to run your code. State also if particular software is needed as prerequisite.
3. In section 5 (Example of application) you have a figure which is completely on top of the text. Can you please fix it.
4. Can you add a line to comment a bit more on what we are observing on the y-axis of figures in section 5.2. Actually the same applies for figures in section 5.4. What do 'ppm C' and 'PgC' mean?

Cheers,
Omar

**Comment by cdgomezo** [comment]
Thank you for your comments Omar. I did the changes you suggested. 

Saludos!
Carlos

**Comment by caterina-doglioni** [comment]
Hi Carlos, 
thanks for the nice notebook! I have a few improvements to suggest. 

1) the Introduction cell is rather chunky - it's clear it's a theory-based one but I think it could benefit from being broken up a little, and possibly a visualisation of "what happens if you don't consider errors" (you could do that with some toy data). This is so the average reader who isn't mathematically inclined can understand first-hand what you're talking about and where you're going. Alternatively if this takes too much time you can add a sentence at the end saying that in the rest of the notebook you're going to demonstrate exactly those effects. 

2) I have a visualisation problem for cell 2 and 5, in the sense that the figure doesn't show properly and only the first part is visible, the rest goes out of the cell. I would suggest changing them to its own cell for better visibility. 

3) You show the results but don't comment much about what you're showing in the figures. If you were to publish this notebook, it would be useful for the reader to have a take-home message after you show the plots beyond simply describing what's in them, so could you add it? 

4) I would suggest to add a "conclusions" cell to write what one has learned by using the notebook. The aim is not completely clear (is it a notebook that shows what you've done? Is it an example of how Bayes theorem works? Should we draw conclusions on the CO2 concentrations?) and having a cell that draws conclusions would help that. 

Thanks!
Caterina

**Comment by cdgomezo** [comment]
Hi Caterina,

Thank you for your feedback. I have updated the notebook with your suggestions. 

Cheers,
Carlos
